### ISSUE TITLE
autogenerate from schema

### ISSUE THREAD

**Issue by ameinhardt** [eclipse/unide.java#2]
@fmisir: do you think an autogenerated java binding from the json schemas would be more accurate or simple?
I'm looking at [jsonschema2pojo](https://github.com/joelittlejohn/jsonschema2pojo/) which can also be used as a [maven plugin](https://github.com/joelittlejohn/jsonschema2pojo/wiki/Getting-Started#the-maven-plugin).

**Comment by ghost** [comment]
Unfortunately the library does not support all features of json schema that are in use in unide. 

For instance the "oneOf" json schema feature used in  [process](https://github.com/eclipse/unide/blob/master/ppmp/ppmp-schema/src/main/resources/org/eclipse/iot/unide/ppmp/v2/process_schema.json)  is not supported. 

[Issue - support one of](https://github.com/joelittlejohn/jsonschema2pojo/issues/392)

**Comment by ameinhardt** [comment]
true. Thanks, @fmisir.
